### ISSUE TITLE
Improve network stack

### ISSUE THREAD

**Issue by polistern** [PurpleBote/pboted#17]
#### Description

At the moment, the application can only work over IPv4.

#### Necessarily

- Add support for IPv6
- Add correct error handling
- Add functionality to handle disconnection: re-create UDP sockets, re-create SAM session

#### Optional

- Consider using Boost instead of STL sockets
- Optimization

**Comment by majestrate** [comment]
If you are shopping around for a new networking lib and event loop I highly recommend https://github.com/skypjack/uvw a header only cpp lib for libuv. It has none of the boost creep that boost brings and libuv is a pretty decent event loop most of the time.

**Comment by r4sas** [comment]
> If you are shopping around for a new networking lib and event loop I highly recommend https://github.com/skypjack/uvw a header only cpp lib for libuv. It has none of the boost creep that boost brings and libuv is a pretty decent event loop most of the time.

Adding another one requirement? What for?

**Comment by majestrate** [comment]
> > If you are shopping around for a new networking lib and event loop I highly recommend https://github.com/skypjack/uvw a header only cpp lib for libuv. It has none of the boost creep that boost brings and libuv is a pretty decent event loop most of the time.
> 
> Adding another one requirement? What for?

I mean if you already are using boost then go with boost. I found it to be small enough that its inclusion is negligible compared to more boost. Just thought to suggest it as it has treated me well in things I have used it in.

**Comment by polistern** [comment]
@majestrate, thanks for the recommendation, but Boost is already used in the project

**Comment by polistern** [comment]
# Status

- [ ] Add support for IPv6 - moved too 0.9.X
- [ ] Add correct error handling - moved too 0.8.X
- [ ] Add functionality to handle disconnection: re-create UDP sockets, re-create SAM session - moved too 0.8.X
- [x] Consider using Boost instead of STL sockets - #28 
- [x] Optimization - DONE
